{{/*
RBAC configuration for Database Operator
Includes: ServiceAccount, ClusterRole, ClusterRoleBinding
*/}}

---
# ServiceAccount for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-operator.serviceAccountName" . }}
  namespace: {{ include "postgres-operator.namespace" . }}
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
# ClusterRole with permissions for the operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "postgres-operator.fullname" . }}-manager-role
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
rules:
  # Database custom resource permissions
  - apiGroups:
      - database.example.com
    resources:
      - databases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.example.com
    resources:
      - databases/finalizers
    verbs:
      - update
  - apiGroups:
      - database.example.com
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update
  # StatefulSet permissions
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Service permissions
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Secret permissions
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
  # Events for status reporting
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
# ClusterRoleBinding to bind the ClusterRole to ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "postgres-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "postgres-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "postgres-operator.serviceAccountName" . }}
    namespace: {{ include "postgres-operator.namespace" . }}

---
# Role for leader election
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "postgres-operator.fullname" . }}-leader-election-role
  namespace: {{ include "postgres-operator.namespace" . }}
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
# RoleBinding for leader election
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgres-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "postgres-operator.namespace" . }}
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "postgres-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "postgres-operator.serviceAccountName" . }}
    namespace: {{ include "postgres-operator.namespace" . }}

